### ISSUE TITLE
Update Google Cast SDK version to 2.5.1

### ISSUE THREAD

**Issue by iheart2code** [ConnectSDK/Connect-SDK-iOS#100]
The biggest thing here is adding support for automatic reconnection on Chromecast.

https://developers.google.com/cast/docs/reference/ios/interface_g_c_k_device_manager#a5b86256fc892b8953ba3b17df9251542

**Comment by iheart2code** [comment]
This is now at version [2.5.1](https://developers.google.com/cast/docs/release-notes)

**Comment by eunikolsky** [comment]
* Test the `dev` and `1.4.1` versions with the updated Cast SDK.
* Update the ConnectSDK `podspec`.

**Comment by iadnan** [comment]
Tested the dev and 1.4.1 version with Google CastSDK v2.5.1 and all the available features works fine.

**Comment by iadnan** [comment]
Sorry found this issue which have broken in previous release https://github.com/ConnectSDK/Connect-SDK-iOS/issues/129 , which is fixed .

**Comment by iadnan** [comment]
Updated the podspec with the new version and verified it .
