### ISSUE TITLE
 getProgramInfoWithSuccess: is unsupported

### ISSUE THREAD

**Issue by iadnan** [ConnectSDK/Connect-SDK-iOS#102]
Get program info service needs to be implemented for Web OS TV and Netcast TV

**Comment by iadnan** [comment]
The second screen API ssap://tv/getChannelProgramInfo is not yet implemented .

**Comment by iheart2code** [comment]
If I recall correctly, there was a bug on the TV side preventing us from successfully implementing this. I had opened a JIRA ticket for it, but it was mostly ignored.

**Comment by iheart2code** [comment]
You can probably find that JIRA ticket by searching for my name. The TV service was returning the incorrect value for the current program or something.

**Comment by iadnan** [comment]
Closing this issue for now. Will reopen the issue if any partner requests for this feature.
