### ISSUE TITLE
AirPlay: Termination after a few minutes in background when video is playing

### ISSUE THREAD

**Issue by eunikolsky** [ConnectSDK/Connect-SDK-iOS#107]
Steps to reproduce:
0. Launch a long video on Apple TV. (see https://github.com/ConnectSDK/Connect-SDK-iOS/issues/106)
1. Lock the device.

Actual behavior:
2. The video stops after a few minutes.
3. The Sampler app has been terminated.

Expected behavior:
2. The whole video is playing.
3. The Sampler app hasn't been terminated and keeps connection with the Apple TV.

The only important log information about the crash:
```
<BKNewProcess: 0x15ee591a0; com.connectsdk.Connect-SDK-Sampler; pid: 4473; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x15ee67570> id: 4473-0694FFA4-0AC8-46BA-B957-E936287DEDD9 name: Called by Connect SDK Sampler, from __52-[AirPlayServiceHTTP sendCommand:withPayload:toURL:]_block_invoke154 process: <BKNewProcess: 0x15ee591a0; com.connectsdk.Connect-SDK-Sampler; pid: 4473; hostpid: -1> permittedBackgroundDuration: 180.000000 reason: finishTask owner pid:4473 preventSuspend  preventIdleSleep  preventSuspendOnSleep 
)}
```

**Comment by eunikolsky** [comment]
Due to the limitation of the iOS, the app cannot run in the background indefinitely, unless it's a navigation app, music player app, etc. If an app is a music player and wants to stream to Apple TV in background, the app should handle that itself. The SDK cannot do that.

**Comment by fadylateef** [comment]
Any new updates ?!!!
