### ISSUE TITLE
Playlist support

### ISSUE THREAD

**Issue by eunikolsky** [ConnectSDK/Connect-SDK-iOS#109]
Add the ability to play an `m3u` playlist on supported platforms (at least, via DLNA). Also, play next and previous methods.

**Comment by iadnan** [comment]
Added features to play m3u files, play list controls (next, previous and jump track) https://github.com/ConnectSDK/Connect-SDK-iOS-Core/commit/e3f45e0022eba0b81d24fe228387197e7c055887
