### ISSUE TITLE
Video/audio looping support

### ISSUE THREAD

**Issue by eunikolsky** [ConnectSDK/Connect-SDK-iOS#112]
Add support for media looping on different platforms. It should be emulated by the SDK if not supported on a particular platform.

See also: https://github.com/ConnectSDK/Connect-SDK-Cordova-Plugin/issues/7

**Comment by eunikolsky** [comment]
* The looping support will be added to the media player on WebOS. We already have the code to use that flag.
* The web media app should get updated on the server, so it should work on Chrome Cast as well. Will need to send this looping flag though.
* DLNA supports the `SetPlayMode` method, which accepts `REPEAT_ONE` and `REPEAT_ALL` among others. If the passed `shouldLoop` flag is `YES`, we'll call this method automatically.

**Comment by eunikolsky** [comment]
Pulling from this release, since the web app changes haven't been tested yet.

**Comment by iadnan** [comment]
Verified looping support in the current Media Player webOSTV app . Works as expected
