### ISSUE TITLE
Nexus Player Support

### ISSUE THREAD

**Issue by eunikolsky** [ConnectSDK/Connect-SDK-iOS#113]
Support media playing on a Nexus Player. It should be already supported by the Cast SDK.

**Comment by iheart2code** [comment]
Make sure you get an actual Nexus consumer device. The Cast SDK was not discovering the ADT-1 unit for me.

**Comment by eunikolsky** [comment]
The Nexus Player doesn't seem to have the Chromecast support in fact. The official YouTube app doesn't show it that way either. It has only the DIAL service, which allows to run YouTube/Netflix.

So the possible solution is to implement a container app for the device to run a web app and communicate with it. Very similar to the Fire TV approach: https://github.com/ConnectSDK/Connect-SDK-iOS/issues/111

Moving this to the next release.

**Comment by iadnan** [comment]
The Nexus player now supports Chromecast and is now supported by ConnectSDK.
