### ISSUE TITLE
Fix warnings for Non-ARC Projects

### ISSUE THREAD

**Issue by jamescahall** [ConnectSDK/Connect-SDK-iOS#119]
Hi,

There are a number of semantic warnings that should be fixed for missing property attributes:
Examples:
Device.h
@property (nonatomic) NSArray *capabilities;

ConnectableDevice.h
@property (nonatomic) NSString *lastKnownIPAddress;
@property (nonatomic) NSString *lastSeenOnWifi;

DiscoveryManager.h
@property (nonatomic) id<ConnectableDeviceStore> deviceStore;

You should either set the appropriate attribute or add:
-Wobjc-property-no-attribute

This causes error on the parent target level and can't be suppressed without code changes to the ConnectSDK module.

Thanks,
James

**Comment by eunikolsky** [comment]
@jamescahall, how do you get these warnings?

I've tried creating a new project, turned off ARC in it, and used `ConnectSDK` from `CocoaPods`:

```
id<ConnectableDeviceStore> store = [DiscoveryManager sharedManager].deviceStore;
```
I don't have the missing attribute warnings. `Xcode 6.1.1 (6A2008a)`

**Comment by jamescahall** [comment]
I'm running the same version so don't know why they aren't showing up for you though I'm not using CocoaPods (just direct integration).

The errors appear in the header files not .m

DeviceService.h
DeviceService.h:95:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
DeviceService.h:95:1: Default property attribute 'assign' not appropriate for non-GC object
ConnectableDevice.h
ConnectableDevice.h:93:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
ConnectableDevice.h:93:1: Default property attribute 'assign' not appropriate for non-GC object
ConnectableDevice.h:96:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
ConnectableDevice.h:96:1: Default property attribute 'assign' not appropriate for non-GC object
DiscoveryManager.h
DiscoveryManager.h:167:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed
DiscoveryManager.h:167:1: Default property attribute 'assign' not appropriate for non-GC object

You just need to change the above to:
Device.h
@property (nonatomic, assign) NSArray *capabilities;

ConnectableDevice.h
@property (nonatomic, assign) NSString *lastKnownIPAddress;
@property (nonatomic, assign) NSString *lastSeenOnWifi;

DiscoveryManager.h
@property (nonatomic, assign) id deviceStore;

OR with ARC

Device.h
@property (nonatomic, weak) NSArray *capabilities;

ConnectableDevice.h
@property (nonatomic, weak) NSString *lastKnownIPAddress;
@property (nonatomic, weak) NSString *lastSeenOnWifi;

DiscoveryManager.h
@property (nonatomic, weak) id deviceStore;

OR if older than 5.0 support required (which I doubt):

Device.h
@property (nonatomic, unsafe_unretained) NSArray *capabilities;

ConnectableDevice.h
@property (nonatomic, unsafe_unretained) NSString *lastKnownIPAddress;
@property (nonatomic, unsafe_unretained) NSString *lastSeenOnWifi;

DiscoveryManager.h
@property (nonatomic, unsafe_unretained) id deviceStore;

OR just suppress the warnings:
-Wobjc-property-no-attribute
@property (nonatomic) NSArray *capabilities;

Thanks,
James

**Comment by eunikolsky** [comment]
Indeed, I can reproduce it, having manually integrated the ConnectSDK.

**Comment by eunikolsky** [comment]
Merged into `dev`. Commit 3b34a6f.
