### ISSUE TITLE
Roku Service Doesn't Support AAC Audio

### ISSUE THREAD

**Issue by jamescahall** [ConnectSDK/Connect-SDK-iOS#123]
Hi,

In investigating the Roku service it appears it relies on a specific channel the connectsdk team has created.  15985.

In doing testing of casting audio, mp3 is working fine but not AAC audio.  It seems you may need to modify logic in your channel app or the iOS / Android code to support AAC audio.

Here is a note from Roku:
For regular AAC from a file server you should be able to do this:
 
Sub main()
Port=createobject("roMessagePort")
Audioplayer=createobject("roAudioPlayer")
Audioplayer.setmessageport(port)
Stream={url:"http:/myserver.com/audio/stream.mp4,streamformat:"mp4"}
Audioplayer.addcontent(stream)
Audioplayer.play()
 
While true
Msg=port.getmessage()
If type(msg)="roAudioPlayerEvent" then
                ?"Message: ";msg.getmessage()
                ?"index: msg.getindex()
End if
End while
End sub
 
Also try streamformat="aac", streamformat="es.aac-adts"

Thanks,
James

**Comment by iheart2code** [comment]
Channel 15985 was created by the Roku team as a simple media player for developers to use. We are simply taking advantage of Roku's channel that is installed on all Roku 2+ devices. We are unable to modify the channel source and we're in communication with that team.

**Comment by jamescahall** [comment]
Ok I see.  Another issue with this solution is that there is no state feedback from the device.  There should be some way to create a socket connection or basic web server on the phone to receive RESTful commands back from the app.

It may be best to ask them for the source so a new app can be made that would have greater capability.

**Comment by iadnan** [comment]
Closing this issue as Roku's player doesn't support AAC audio . For Roku events support a different issue already exists https://github.com/ConnectSDK/Connect-SDK-iOS/issues/167
