### ISSUE TITLE
Video is not playing after upgrading the Roku firmware to 6.1

### ISSUE THREAD

**Issue by iadnan** [ConnectSDK/Connect-SDK-iOS#124]
With Roku firmware 6.1 update, the Play To Roku video no longer works.The "Play on Roku" screen is displayed on the cast device, the buffering bar is displayed for an instance and shortly after the video is dismissed and the Roku main menu is displayed.

**Comment by iadnan** [comment]
Checked the Roku app on iPhone and took a tcpdump . looks like the app creates a dynamic playlist file (.m3u8) which is then hosted on the device.

**Comment by iadnan** [comment]
Fixed the issue by creating a playlist and hosting on web server on the device when video is played.

https://github.com/ConnectSDK/Connect-SDK-iOS-Core/commit/f6dc0e1fd9f5ccf23984989d443ebbc9574c60c1

**Comment by iadnan** [comment]
Looks like Roku fixed their issue and broken our fix

**Comment by eunikolsky** [comment]
Related issue: https://github.com/ConnectSDK/Connect-SDK-Android/issues/232

**Comment by eunikolsky** [comment]
Reverted the change: https://github.com/ConnectSDK/Connect-SDK-iOS/commit/5d7c03e69dd5a45c690ec70f0797c4826260aa63. Tested with the latest update `6.1.5609`.
