### ISSUE TITLE
Expose DevicePicker TableViewController for Modification

### ISSUE THREAD

**Issue by jamescahall** [ConnectSDK/Connect-SDK-iOS#125]
Hi,

Currently the device picker is very basic and doesn't allow customization without modifying connectsdk source.  It would be great if there was a method exposed so that the tableviewcontroller could be modify for styling or subclasses completely.

Thanks,
James

**Comment by iadnan** [comment]
@jamescahall  you can implement your own view/device picker to show list of devices . To get the list of devices discovered you have to implement and override the DiscoveryManagerDelegate methods in your interface.

- (void) discoveryManager:(DiscoveryManager *)manager didFindDevice:(ConnectableDevice *)device;
- (void) discoveryManager:(DiscoveryManager *)manager didLoseDevice:(ConnectableDevice *)device;
- (void) discoveryManager:(DiscoveryManager *)manager didUpdateDevice:(ConnectableDevice *)device;
