### ISSUE TITLE
webOSTV: Input Picker is not launching

### ISSUE THREAD

**Issue by khk624** [ConnectSDK/Connect-SDK-iOS#131]
webOSTV has remove old way to launch input picker and add new ssap method.
We need to wait for second screen gateway handling the uri first.

new ssap method will be "ssap://com.webos.surfacemanager/showInputPicker"

**Comment by eunikolsky** [comment]
The same issue on Android: https://github.com/ConnectSDK/Connect-SDK-Android/issues/208

**Comment by frolov-alexey** [comment]
Currently we launch "com.webos.app.inputpicker" application, but for newer version (> 2.0) we should launch an "com.webos.app.inputmgr" application instead.

**Comment by eunikolsky** [comment]
Fixed in https://github.com/ConnectSDK/Connect-SDK-iOS/commit/9c42c7ef4a46f6db8d5491401d93e09be2aacb61. Released in 1.5.0.
