### ISSUE TITLE
Error in WebOSTVServiceSocketClient.m

### ISSUE THREAD

**Issue by write2art** [ConnectSDK/Connect-SDK-iOS#132]
When i try to connect to webOS device i end up with error:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

Line 72
- (NSDictionary *) manifest
{
    NSDictionary *infoDic = [[NSBundle mainBundle] infoDictionary];   
    return @{
             @"manifestVersion" : @(1),
             @"appId" : [infoDic objectForKey:@"CFBundleIdentifier"],
             @"vendorId" : @"",
             @"localizedAppNames" : @{
                     @"" : [infoDic objectForKey:@"CFBundleDisplayName"]
                     },
             @"permissions" : self.service.permissions
             };
}

If i just comment this line:
             @"localizedAppNames" : @{
                     @"" : [infoDic objectForKey:@"CFBundleDisplayName"]
                     },

everything is working as expected.

**Comment by eunikolsky** [comment]
Fixed by https://github.com/ConnectSDK/Connect-SDK-iOS-Core/commit/53aca1cae88f7e25bfed043786743fc168108cef, available in `dev` branch.

@write2art, please check.
