### ISSUE TITLE
Airplay: [ConnectableDevice.mediaPlayer playMedia:] doesn't return if Apple TV is asleep

### ISSUE THREAD

**Issue by ericwlange** [ConnectSDK/Connect-SDK-iOS#137]
Connect to an Apple TV via Airplay
Attempt to play a media file with [ConnectableDevice.mediaPlayer playMedia:]
Neither the success:^{} nor failure:^{} completion handlers get called if the Apple TV is currently asleep

Expected behavior: ideally wake the Apple TV up, or at worst, fail

**Comment by eunikolsky** [comment]
@ericwlange, I couldn't reproduce this issue. Here are my steps:
0. On Apple TV, go to Settings, select Sleep Now. The TV shows no signal on HDMI.
1. Install [the Sampler app](https://github.com/ConnectSDK/Connect-SDK-iOS-API-Sampler), go to iOS Settings, Sampler, AirPlay Mode, select Media.
2. Run the Sampler app, connect to the Apple TV, click the Video button.

Result: the Apple TV wakes up and starts playing the video. The `success` handler is called.

Could you provide any extra information?

Apple TV MC572LL, Software 6.2.1.

**Comment by ericwlange** [comment]
I just looked through the sampler code, and I had left out this line in my project:

_discoveryManager.pairingLevel = DeviceServicePairingLevelOn;
(which, incidentally, I had to use ConnectableDevicePairingLevelOn -- I assume this changed recently?)

I added it and now it works great!  Does it make sense that forgetting this line would make it work sometimes and not others?

**Comment by eunikolsky** [comment]
Very interesting. I tried commenting that line in the Sampler, reinstalling it, and the playing video still wakes up the Apple TV. The `pairingLevel` property isn't used in `AirPlayService` in fact, so I don't know how it could change the behavior.

Regarding the enum, in the `1.4.2` release, we deprecated the `ConnectableDevicePairingLevel` enum and provided `DeviceServicePairingLevel` instead, so you should be able to use it. https://github.com/ConnectSDK/Connect-SDK-iOS-Core/blob/38a3f16d0aac1672df8cf506aa09259a27a8dfad/Services/DeviceService.h#L29-38
