### ISSUE TITLE
The file you've selected is not currently supported

### ISSUE THREAD

**Issue by kentdome** [ConnectSDK/Connect-SDK-iOS#139]
Connect SDK Sampler -> Connecting to an Samsung 65" , beaming the photo works but when trying to display the test video (Blender Open Movie Project) the TV displays "The file you've selected is not currently supported".

2015-03-12 09:34:17.295 Connect SDK Sampler[1476:431935] writing as default Blender Open Movie Project to the key videoDescription
2015-03-12 09:34:17.295 Connect SDK Sampler[1476:431935] writing as default http://ec2-54-201-108-205.us-west-2.compute.amazonaws.com/samples/media/video.mp4 to the key videoPath
2015-03-12 09:34:17.296 Connect SDK Sampler[1476:431935] writing as default http://ec2-54-201-108-205.us-west-2.compute.amazonaws.com/samples/media/videoIcon.jpg to the key videoThumbPath
2015-03-12 09:34:17.296 Connect SDK Sampler[1476:431935] writing as default video/mp4 to the key videoMimeType

Verbose log:

[DEBUG] Did connect
[DEBUG] Did start background task
[DEBUG] Did open connection on socket 14
[DEBUG] Did open connection on socket 15
[DEBUG] Connection received 636 bytes on socket 13
[DEBUG] Connection received 636 bytes on socket 14
[DEBUG] Connection on socket 14 preflighting request "NOTIFY /smp_27_" with 636 bytes body
[DEBUG] Connection on socket 13 preflighting request "NOTIFY /smp_27_" with 636 bytes body
[DEBUG] Connection on socket 14 processing request "NOTIFY /smp_27_" with 636 bytes body
[DEBUG] Connection on socket 13 processing request "NOTIFY /smp_27_" with 636 bytes body
[DEBUG] Connection received 636 bytes on socket 15
[DEBUG] Connection on socket 15 preflighting request "NOTIFY /smp_27_" with 636 bytes body
[DEBUG] Connection on socket 15 processing request "NOTIFY /smp_27_" with 636 bytes body
[DEBUG] Connection sent 122 bytes on socket 14
[DEBUG] Did close connection on socket 14
[VERBOSE] [192.168.2.6:49291] 192.168.2.102:57023 200 "NOTIFY /smp_27_" (636 | 122)
[DEBUG] Connection sent 122 bytes on socket 13
[DEBUG] Did close connection on socket 13
[VERBOSE] [192.168.2.6:49291] 192.168.2.102:57022 200 "NOTIFY /smp_27_" (636 | 122)
[DEBUG] Connection sent 122 bytes on socket 15
[DEBUG] Did close connection on socket 15
[VERBOSE] [192.168.2.6:49291] 192.168.2.102:57024 200 "NOTIFY /smp_27_" (636 | 122)
[DEBUG] Did open connection on socket 13
[DEBUG] Did open connection on socket 14
[DEBUG] Did open connection on socket 15
[DEBUG] Connection received 773 bytes on socket 13
[DEBUG] Connection on socket 13 preflighting request "NOTIFY /smp_27_" with 773 bytes body
[DEBUG] Connection received 773 bytes on socket 15
[DEBUG] Connection on socket 13 processing request "NOTIFY /smp_27_" with 773 bytes body
[DEBUG] Connection on socket 15 preflighting request "NOTIFY /smp_27_" with 773 bytes body
[DEBUG] Connection on socket 15 processing request "NOTIFY /smp_27_" with 773 bytes body
[DEBUG] Connection received 773 bytes on socket 14
[DEBUG] Connection on socket 14 preflighting request "NOTIFY /smp_27_" with 773 bytes body
[DEBUG] Connection on socket 14 processing request "NOTIFY /smp_27_" with 773 bytes body
[DEBUG] Connection sent 122 bytes on socket 13
[DEBUG] Connection sent 122 bytes on socket 15
[DEBUG] Did close connection on socket 13
[DEBUG] Did close connection on socket 15
[VERBOSE] [192.168.2.6:49291] 192.168.2.102:57025 200 "NOTIFY /smp_27_" (773 | 122)
[VERBOSE] [192.168.2.6:49291] 192.168.2.102:57027 200 "NOTIFY /smp_27_" (773 | 122)
[DEBUG] Connection sent 122 bytes on socket 14
[DEBUG] Did close connection on socket 14
[VERBOSE] [192.168.2.6:49291] 192.168.2.102:57026 200 "NOTIFY /smp_27_" (773 | 122)
[DEBUG] Did disconnect
[DEBUG] Did end background task

Any ideas? Did the mimetype change?

**Comment by eunikolsky** [comment]
@kentdome, we have the same issue with a couple of our Samsung TVs. It returns no error, but doesn't actually play the video and displays the message. Apparently, different models support different codecs. The mime-type hasn't changed, the video didn't work before either.

**Comment by eunikolsky** [comment]
Closing now. @kentdome, please comment if you have any ideas.
