### ISSUE TITLE
[Netcast] Rewind/Fast Forward don't work but they are returned in capabilities

### ISSUE THREAD

**Issue by softvision-teodorabadea** [ConnectSDK/Connect-SDK-iOS#140]
Using Connect SDK version 1.4.3, when connected to a Netcast device when I query if the fast forward is supported using:
       [self.LGDevice hasCapability:kMediaControlFastForward]
and I receive YES, but when I actually try to use the functionality:
       [self.mediaControl fastForwardWithSuccess:^(id responseObject) {}
                                              failure:^(NSError *error) {}];
I always receive in the completion block the following error:
       Error Domain=com.lge.connectsdk.error 
       Code=1100 "This feature is not supported." 
       UserInfo=0x17738b30 {NSLocalizedDescription=This feature is not supported.}

Please let me know if any additional info is required.
![img_4463](https://cloud.githubusercontent.com/assets/7487944/6982164/3d31bf78-da16-11e4-872c-53acfeeb3cc6.JPG)

**Comment by iadnan** [comment]
Fixed as part of https://github.com/ConnectSDK/Connect-SDK-iOS-Core/commit/7d55ee61b557102bc37ebf8747d30ce0827112d0
