### ISSUE TITLE
Error handling for MediaCommands for the Mediaplayer in WebOSTv

### ISSUE THREAD

**Issue by iadnan** [ConnectSDK/Connect-SDK-iOS#150]
Error handling for media player commands should be implemented for webOS tv . When a invalid mime type or a invalid url is sent to WebOSTV media player it returns "connectsdk.media-error" .

**Comment by eunikolsky** [comment]
Implemented in https://github.com/ConnectSDK/Connect-SDK-iOS/commit/5d1695ae0e2c2576f13de677f26a7d1917e4bb26. Released in 1.5.0.
