### ISSUE TITLE
Joining Chromecast's WebApp Doesn't Work Anymore

### ISSUE THREAD

**Issue by martinobonfiglioli** [ConnectSDK/Connect-SDK-iOS#159]
I'm using latest SDK version, after joining Chromecast's WebApp 

```objective-c
- (void) joinWebAppWithId:(NSString *)webAppId success:(WebAppLaunchSuccessBlock)success failure:(FailureBlock)failure;
```

this method never call the completion handler

```objective-c
- (void) connectWithSuccess:(SuccessBlock)success failure:(FailureBlock)failure;
```

Could someone check if this is an issue or maybe i'm doing something wrong?
Thanks.

**Comment by iadnan** [comment]
@martinobonfiglioli  I tested it in our sampler app https://github.com/ConnectSDK/Connect-SDK-iOS-API-Sampler , and it seems to be calling the completion handler . Can you please verify in the sampler app . Are you calling launchWebApp  prior to calling joinWebAppWithId ? if not you should do it. Thanks.

```objective-c
- (void)launchWebApp:(NSString *)webAppId success:(WebAppLaunchSuccessBlock)success failure:(FailureBlock)failure
```

**Comment by martinobonfiglioli** [comment]
@iadnan 
if I call joinWebAppWithId: after launchWebApp: I'm try to join to my own webAppSession, isn't it?
So I solved my issue without call connectWithSuccess:

I simply call joinWebAppWithId: if the completion handler respond with success I'm already connected to webAppSession as slave, according with Connect-SDK-iOS-API-Sampler.

Thanks for the quick reply/help!
