### ISSUE TITLE
Make "+ (LaunchSession *) launchSessionFromJSONObject:(NSDictionary *)json" method visible

### ISSUE THREAD

**Issue by martinobonfiglioli** [ConnectSDK/Connect-SDK-iOS#160]
As specified in documentation: http://connectsdk.com/docs/ios/resuming-apps/

I need 

```objective-c
+ (LaunchSession *) launchSessionFromJSONObject:(NSDictionary *)json
```

visible to restore webAppSession for background / foreground switch.

Thanks.

**Comment by iadnan** [comment]
Added Missing API https://github.com/ConnectSDK/Connect-SDK-iOS-Core/commit/0450d568938de1a2b7d9ea10b5f5b01acf06ed4c
