### ISSUE TITLE
WebOS: Unable to play message not dismissed when playing a supported file.

### ISSUE THREAD

**Issue by softvision-raducostea** [ConnectSDK/Connect-SDK-iOS#161]
On Web OS, if I try to play a file that is not supported, a message is shown on the TV. When I try to play a different file, that is supported, the file plays, but the message doesn't go away. There should probably be a way of dismissing those type of alerts.

Please see the attatched screenshots.
![unable_to_play](https://cloud.githubusercontent.com/assets/12232154/7955706/0dc76240-09e3-11e5-9afd-fd488fac9fb7.png)
![about](https://cloud.githubusercontent.com/assets/12232154/7955762/8179f860-09e3-11e5-926d-1ccf91e9b738.jpg)

**Comment by eunikolsky** [comment]
@softvision-raducostea, the player has been updated: if you play a correct file after the wrong one, the alert will be dismissed automatically. Please verify the fix.

**Comment by softvision-raducostea** [comment]
Thanks @eunikolsky . I tested with 1.4.4 and it is now fixed.
