### ISSUE TITLE
closeWebApp should use ssap://webapp/closeWebApp always

### ISSUE THREAD

**Issue by Andolamin** [ConnectSDK/Connect-SDK-iOS#162]
closeWebApp in WebOSTVService should use ssap://webapp/closeWebApp (current fallback behavior for if the webAppSession is not connected) in all cases. This will correct some confusing behavior with current implementation.

**Comment by eunikolsky** [comment]
See also: https://github.com/ConnectSDK/Connect-SDK-Android/issues/261

**Comment by iadnan** [comment]
Fixed  in https://github.com/ConnectSDK/Connect-SDK-iOS-Core/commit/93a2abde29d8316d1928eae5e2e7d2163614e312
