### ISSUE TITLE
Cannot play video/audio on Roku with latest update

### ISSUE THREAD

**Issue by eunikolsky** [ConnectSDK/Connect-SDK-iOS#166]
Latest update on Roku has broken audio & video playing. Our previous fix (https://github.com/ConnectSDK/Connect-SDK-iOS/issues/124) doesn't work this time.
On Roku 3 (6.2.3467), the player displays for a second, then exits.
On Roku Stick (6.2.3491), the video player hangs saying "retrieving", and then Roku restarts after ~15 seconds. But the audio is played for one second, then the player exits.

Android issue: https://github.com/ConnectSDK/Connect-SDK-Android/issues/279

**Comment by omody** [comment]
Yes I can reproduce on iOS as well...

**Comment by eunikolsky** [comment]
The official Roku app works though. We'll have to figure out how it works.

**Comment by eunikolsky** [comment]
We could actually detect this error if we supported events (#167).

**Comment by eunikolsky** [comment]
Apparently, the latest version stops playing a media if the event URL is incorrect/inaccessible/doesn't reply/something wrong. Since we don't support events now (#167), the fix is to use "(null)" for the "h" parameter.

**Comment by eunikolsky** [comment]
Fixed in `dev`.

**Comment by manifestinteractive** [comment]
verified dev fixes this issue for me too

**Comment by eunikolsky** [comment]
@manifestinteractive, great, thanks for confirming!
