### ISSUE TITLE
Chromecast: Duration not cleared

### ISSUE THREAD

**Issue by steve228uk** [ConnectSDK/Connect-SDK-iOS#171]
It seems that when you jump from one video to another the duration of the previous video isn't cleared. Even when we actively call `launchObject?.session.closeWithSuccess` the duration isn't cleared.

**Comment by eunikolsky** [comment]
@steve228uk, can you please write the steps to reproduce this issue?

**Comment by steve228uk** [comment]
1. Launch video with `playMediaWithMediaInfo`
2. Store the `MediaLaunchObject`
3. Fetch duration from the `MediaLaunchObject.mediaControl`
4. Set `MediaLaunchObject` reference to nil
5. Repeat 1 -> 3

Expected: New duration or error

What actually happens: Old duration is returned.

The same thing happens for the position.

**Comment by steve228uk** [comment]
Even after calling `closeWithSuccess` the old launchObject is returned immediately and then changed later when the video has loaded.

**Comment by eunikolsky** [comment]
@steve228uk, I couldn't reproduce the bug so far. I've uploaded a quick and dirty project here: https://github.com/eunikolsky/CastDurationCheck/tree/dev. Can you check the project and/or publish yours?

**Comment by steve228uk** [comment]
@eunikolsky Cheers, I'll take a look tomorrow

**Comment by steve228uk** [comment]
Closing this one as your example couldn't replicate it.

**Comment by eunikolsky** [comment]
@steve228uk, thanks for the confirmation.
