### ISSUE TITLE
Roku: crash on getting app list

### ISSUE THREAD

**Issue by eunikolsky** [ConnectSDK/Connect-SDK-iOS#175]
The original post is here: https://github.com/ConnectSDK/Connect-SDK-iOS-API-Sampler/issues/23#issuecomment-133306857

Crash on this line: `[apps enumerateObjectsUsingBlock:^(NSDictionary *appInfoDictionary, NSUInteger idx, BOOL *stop)`
>The Roku firmware version is 6.2.build3467 and ConnectSDK version is 1.5.0.

**Comment by eunikolsky** [comment]
@yuchin067, it seems your Roku device has only one app, so that `apps.app` is parsed as a dictionary, instead of an array. Can you please log the [`appListDictionary` value](https://github.com/ConnectSDK/Connect-SDK-iOS-Core/blob/1.5.0/Services/RokuService.m#L406) and upload it here?

**Comment by eunikolsky** [comment]
@yuchin067, the bug should be fixed in this branch: https://github.com/eunikolsky/Connect-SDK-iOS-Core/tree/bugfix/175_roku_apps_crash Please checkout the branch and verify in your setup.

**Comment by yuchin067** [comment]
It work around now, thanks for your help.

**Comment by eunikolsky** [comment]
Merged into `dev` in https://github.com/ConnectSDK/Connect-SDK-iOS/commit/210835374722044bd6e364dc656ea0601ee8bf75 and https://github.com/ConnectSDK/Connect-SDK-iOS-Lite/commit/08b5355e2c6010ca4824ec39b781d8cae49a684d
