### ISSUE TITLE
Check the SDK on Xcode 7 and iOS 9

### ISSUE THREAD

**Issue by eunikolsky** [ConnectSDK/Connect-SDK-iOS#176]

**Comment by martinobonfiglioli** [comment]
To build the SDK under iOS9 with Xcode 7 you have to add:

"-licucore"
"-lz"

in Build Settings -> Other Linker Flag

because of Xcode bug explain here:
https://forums.developer.apple.com/message/8609#8609

**Comment by eunikolsky** [comment]
@martinobonfiglioli, I'm able to build the library/framework itself in Xcode 7.1 beta without changing anything. These changes may be required for an app using ConnectSDK, but I can build the sampler with `libz.dylib`, `libicucore.dylib`, and `libc++.tbd` just fine.

**Comment by iadnan** [comment]
tried to build framework with new Xcode 7.0 without any issues.  Closing this issue
