### ISSUE TITLE
iOS 9: SSDP discovery doesn't work

### ISSUE THREAD

**Issue by eunikolsky** [ConnectSDK/Connect-SDK-iOS#177]
We use HTTP to connect with local SSDP-discovered devices, and that is blocked by default in iOS 9. Here is a warning in logs:
> App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

**Comment by eunikolsky** [comment]
Adding this to the app's `Info.plist` file fixes this for now, although not recommended:
```xml
<key>NSAppTransportSecurity</key>
<dict>
	<key>NSAllowsArbitraryLoads</key>
	<true/>
</dict>
```

The other thing is to check whether devices support HTTPS (via DLNA, DIAL, Netcast, etc.).

**Comment by iadnan** [comment]
Closing the issue as there is a work around as mentioned above
