### ISSUE TITLE
DiscoveryManager doesn't monitor WiFi changes

### ISSUE THREAD

**Issue by eunikolsky** [ConnectSDK/Connect-SDK-iOS#181]
`-[DiscoveryManagerDelegate discoveryManager:didFailWithError:]` isn't called anywhere from `DiscoveryManager`. It's supposed to be called when WiFi becomes disabled, for instance. 

On Android, the WiFi is checked only when [discovery is started](https://github.com/ConnectSDK/Connect-SDK-Android-Core/blob/dev/src/com/connectsdk/discovery/DiscoveryManager.java#L534).

1. Should `DiscoveryManager` shutdown all discovery providers and services when WiFi is down?
2. Should it automatically stop itself in that case?
3. Should it automatically start when WiFi is on?

**Comment by iadnan** [comment]
This feature is already there . Check -(void)detectSSIDChange in DiscoveryManager .
