### ISSUE TITLE
Include of non-modular header inside framework module

### ISSUE THREAD

**Issue by steve228uk** [ConnectSDK/Connect-SDK-iOS#184]
Hi guys,

Trying to use ConnectSDK in a Swift 2.0 project with the latest release (1.6). I'm getting a few errors being thrown all relating to

`Include of non-modular header inside framework module 'ConnectSDK.CastService'`
`Include of non-modular header inside framework module 'ConnectSDK.CastServiceChannel'`
`Include of non-modular header inside framework module 'ConnectSDK.CTASIDataCompressor'`

These seem to be due to import of `<GoogleCast/GoogleCast.h>` and `<zlib.h>`

**Comment by eunikolsky** [comment]
@steve228uk, you can try the `ConnectSDKDynamic` target in this branch: https://github.com/ConnectSDK/Connect-SDK-iOS/tree/feature/carthage_support Those errors are fixed there; it's pre-1.6.0 though.

**Comment by steve228uk** [comment]
Hey @eunikolsky, cheers! I ended up installing manually and not through Cocoapods as I had a few issues. Think this maybe an Xcode 7 + Cocoapods thing.

**Comment by klevison** [comment]
Same error for me, I can't install ConnectSDK with xcode7

**Comment by bauloc** [comment]
Still same issues

**Comment by San-Jeevan** [comment]
same issues

**Comment by AlexBlack559** [comment]
Same issue

**Comment by fadylateef** [comment]
Have any one successfully could integrate it into Swift till NOW ?!

**Comment by steve228uk** [comment]
@fadylateef I'm using it in [this project](https://github.com/TryFetch/Fetch) perhaps that could help give you some pointers.

**Comment by fadylateef** [comment]
@steve228uk Does fetch app casts successfully on Smart TVs , like LG which uses WebOS ?
I opened the project and could not run it 😢  It has a lot of missing .h files and converting the syntax gives many errors.

**Comment by steve228uk** [comment]
@fadylateef It does, casts to smart TVs, Fire TV stick etc. The project needs updating to Swift 3/4
