### ISSUE TITLE
Can’t find Roku, DLNA device in iOS9

### ISSUE THREAD

**Issue by yuchin067** [ConnectSDK/Connect-SDK-iOS#186]
I upgrade iOS version to iOS9, but I can’t find Roku, DLNA device.
ConnectSDK version is 1.6.0.

**Comment by iadnan** [comment]
Please check fix mentioned here https://github.com/ConnectSDK/Connect-SDK-iOS/issues/177

**Comment by yuchin067** [comment]
It work fine now, thanks.
