### ISSUE TITLE
sending a toast with image

### ISSUE THREAD

**Issue by spambus** [ConnectSDK/Connect-SDK-iOS#188]
how can you send a toast message including an icon image?

this part:

- (void) showToast:(NSString *)message iconData:(NSString *)iconData iconExtension:(NSString *)iconExtension success:(SuccessBlock)success failure:(FailureBlock)failure;

the iconData string, can this be from an external URL source?

or do the images need to be located on the TV's internal storage?

and the iconExtension string is for setting the image extension like: "png" or ".png" or "PNG"?

what is the correct way?

and what image extensions are supported? png? jpg? gif?

I tried a lot of options but non work...

**Comment by iadnan** [comment]
the iconData string is base64 encoded string. You need to convert the image into base64 encoded string and send it witht he showToast API. 

You can use the following code to convert UIImage to base 64.

- (NSString *)encodeToBase64String:(UIImage *)image {
    return [UIImagePNGRepresentation(image) base64EncodedStringWithOptions:NSDataBase64Encoding64CharacterLineLength];
}

**Comment by spambus** [comment]
but how does it work?

the image url is converted to a base64 string?

and the tv loads to image from the url

or the whole image is converted to a base64 string?

and the binary of the image is send to the tv i base64 format?

for example here you can convert images to base64:

http://www.askapache.com/online-tools/base64-image-converter/

what is send to the TV to display a message with icon is:

{"type":"request","id":1,"uri":"ssap://system.notifications/createToast","payload":{"message":"Hallo", "iconData": "what goes here" , "iconExtension": "png"}}

what is the correct parameter for iconExtension as I asked before? is it "png", ".png" is it case sensitive? or does it need to be something else?

**Comment by spambus** [comment]
nevermind found out how it works

**Comment by iadnan** [comment]
@spambus it is not the image url but the image converted to base64 string and is set to "iconData". I have already provided the method to convert a UIImage to base 64 string.

For sample please check https://github.com/ConnectSDK/Connect-SDK-iOS-API-Sampler (https://github.com/ConnectSDK/Connect-SDK-iOS-API-Sampler/blob/master/ConnectSDKSampler/Content/AppsViewController.m)

**Comment by iadnan** [comment]
@spambus thats great

**Comment by spambus** [comment]
Thanx
