### ISSUE TITLE
iOS 9 SSL issue

### ISSUE THREAD

**Issue by jbouaziz** [ConnectSDK/Connect-SDK-iOS#191]
Hi,

I've been trying to retrieve images from a WebOS TV for `ExternalInputInfo` and `AppInfo` classes but I keep getting SSL certificate issues:
`NSURLSession/NSURLConnection HTTP load failed (kCFStreamErrorDomainSSL, -9813)`.

Based on [`SecureTransport.h`](http://www.opensource.apple.com/source/libsecurity_ssl/libsecurity_ssl-36800/lib/SecureTransport.h) the 9813 code is referring to `cert chain not verified by root`.

That's the link the server returns me:
https://192.168.0.23:3001/resources/b3ad032326e96c0b870c55129048e9a303f1a645/HDMI_2.png

That's the piece of code I'm using to retrieve an image:

```
if let data = NSData(contentsOfURL: inputInfo.iconURL),
    image = UIImage(data: data) {

    cell.accessoryView = UIImageView(image: image)

} else {
    cell.accessoryView = nil
}
```

I've also disabled ATS in the plist file:

```
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSAllowsArbitraryLoads</key>
    <true/>
</dict>
```

Am I the only one experiencing this? How could I retrieve images?

**Comment by iadnan** [comment]
@jbouaziz Please try the following work around. Replace "https" with "http" and "3001" to "3000" . in the iconURL.

```
NSString *newURLString = [inputInfo.iconURL.absoluteString stringByReplacingOccurrencesOfString:@"https" withString:@"http"];
    newURLString = [newURLString stringByReplacingOccurrencesOfString:@"3001" withString:@"3000"];
iconURL = [NSURL URLwithString:newURLString];
 ```

**Comment by jbouaziz** [comment]
Hey @iadnan,
It seems to be working for `ExternalInputInfo` which is great, but not for `AppInfo` icons. Do you know how to fix that?
Thanks!

**Comment by simoa** [comment]
@jbouaziz Hi, did you managed to get the app icon showing after all ? Thank you

**Comment by simoa** [comment]
@jbouaziz Hi, I know it has been awhile now, did you manage to find a way to get the app icons ?

**Comment by jbouaziz** [comment]
@simoa I don't remember, sorry
