### ISSUE TITLE
iOS 14.5 - Samsung TV's won't show up anymore in device picker

### ISSUE THREAD

**Issue by dylancom** [ConnectSDK/Connect-SDK-iOS#229]
Recently my Samsung TV's won't show up anymore when they are turned on already before opening the device picker. 
This was working fine before so I'm not sure if this is related to an iOS update.
If I turn on a TV after opening the device picker, it will show up fine though.

Probably related to: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_networking_multicast

**Comment by dylancom** [comment]
Requesting a Multicast Networking Entitlement fixed the issue.

**Comment by volodymyr-koff** [comment]
> Requesting a Multicast Networking Entitlement fixed the issue.

Hey. Did adding com.apple.developer.networking.multicast to entitlements file solve the issue for you? Because it did not for me. Still my Samsung SmartTV cannot be found, only apple devices, such us Mac book
