### ISSUE TITLE
Failed to scan device on iOS 16

### ISSUE THREAD

**Issue by iOS090Bravo** [ConnectSDK/Connect-SDK-iOS#253]
When we use an iOS 16 device, it doesn't seem to be able to find any.
In iOS 15.x everything is fine
Does it really solve the problem if we enable the entitlement:
"com.apple.developer.networking.multicast"
Thanks

**Comment by viettu3598** [comment]
same issue

**Comment by nicolasanteojos** [comment]
Can anyone solve this?

**Comment by viettu3598** [comment]
> Can anyone solve this?
You can ask apple to allow access to MultiCast Network

**Comment by nicolasanteojos** [comment]
Thanks!

> > Can anyone solve this?
> > You can ask apple to allow access to MultiCast Network

Thanks!

**Comment by sivaprasadkv** [comment]
Yes, this issue has been resolved by enabling Multicast Networking (com.apple.developer.networking.multicast).
Request Apple to enable this advanced capability in your developer account for a particular Apple identifier. 
Provide proper justification on using this capability in your app.

URL to make a request is: https://developer.apple.com/contact/request/networking-multicast

Ones Apple approved and enabled it, enable this capability to your bundle identifier in your developer account.
After this, add com.apple.developer.networking.multicastv = YES in your entitlement file in your project.

After all this, your app discovers all the devices immediately.
Enjoy Coding! :)
