### ISSUE TITLE
Error building project with ConnectSDK pod

### ISSUE THREAD

**Issue by vladimirkoff** [ConnectSDK/Connect-SDK-iOS#256]
I am having an issue building my project with ConnectSDK installed. I've come across such errors before, but increasing deployment target for all of the dependencies used to help. But I've tried this now - did not help. I've been struggling with this error for 3 days now. Maybe someone has a solution? Would be extremely grateful. 

<img width="883" alt="Screenshot 2023-09-29 at 10 53 38" src="https://github.com/ConnectSDK/Connect-SDK-iOS/assets/115025494/574afeed-913b-439b-a8ae-3c2bb98274bf">

An my Podfile

` platform :ios, '14.0'

target 'ConnectTest' do

  use_frameworks!

  
  pod 'ConnectSDK'

end`

**Comment by iOS090Bravo** [comment]
with google cast freamwork you need an physical device to build.

**Comment by vladimirkoff** [comment]
> with google cast framework you need an physical device to build.

Oh, got it friend, thanks! But when launching on physical device, it doesn't search for any device in the network and instead returns such log every second: 

<img width="535" alt="Screenshot 2023-10-11 at 10 36 54" src="https://github.com/ConnectSDK/Connect-SDK-iOS/assets/115025494/2e0c1b6e-42dd-47ec-bff7-a47de92bc5dd">

Maybe you have any ides how to solve this?

**Comment by vladimirkoff** [comment]
> with google cast framework you need an physical device to build.

Oh, got it, thanks friend! But when launching on physical device, it doesn't search for any devices in the network and returns such log every second: 

<img width="563" alt="Screenshot 2023-10-11 at 10 38 55" src="https://github.com/ConnectSDK/Connect-SDK-iOS/assets/115025494/27bde5d3-cf5f-4873-965c-6c5ec3b29dff">

Maybe any ideas how to solve it?
