### ISSUE TITLE
Attempt to address Mouse latency issues on Netcast

### ISSUE THREAD

**Issue by iheart2code** [ConnectSDK/Connect-SDK-iOS#47]
See https://github.com/ConnectSDK/Connect-SDK-Android/issues/33

**Comment by eunikolsky** [comment]
I've checked the Sampler `1.4.1` app with Netcast TVs `39LN5700-LN` and `32LM6200-UE`. The cursor movement is pretty smooth on both TVs and is compared with the official `LG TV Remote` app.
