### ISSUE TITLE
Netcast DLNA FWD/RWD

### ISSUE THREAD

**Issue by henrylevak** [ConnectSDK/Connect-SDK-iOS#61]
Place holder.. we need to do something better for Netcast DLNA fwd/rwd support. If system doesn't support we shouldn't show it.

**Comment by eunikolsky** [comment]
Currently, the SDK has static capabilities, which indicate that FWD & RWD are implemented in Netcast TVs. They support a keycode for FWD and RWD actions, and we send those in `NetcastTVService`.
