### ISSUE TITLE
Add support for Samsung Convergence?

### ISSUE THREAD

**Issue by iheart2code** [ConnectSDK/Connect-SDK-iOS#68]
See relevant API docs.

- [Convergence API](http://www.samsungdforum.com/Guide/art00027/index.html)
- [Messaging](http://www.samsungdforum.com/Guide/art00028/index.html)
- [Discovery & Pairing](http://www.samsungdforum.com/Guide/ref00003/index.html)

**Comment by eunikolsky** [comment]
I think we'll go with the newer Multiscreen SDK first: https://github.com/ConnectSDK/Connect-SDK-iOS/issues/67
