### ISSUE TITLE
Look into CastService failure on relaunch

### ISSUE THREAD

**Issue by iheart2code** [ConnectSDK/Connect-SDK-iOS#74]
Possibly need to call `_castDeviceManager = nil;` after `deviceDisconnectWithError`.

Error being returned by steps is

```
display video failure: Error Domain=com.lge.connectsdk.error Code=1001 "API error: (null)" UserInfo=0x170272640
```

**Comment by renevdkooi** [comment]
I'm getting this error even on the first load. The device is properly selected and is not null, but this error shows up just after connecting.
