### ISSUE TITLE
Move ConnectableDevicePairingLevel static property to the DeviceService class

### ISSUE THREAD

**Issue by iheart2code** [ConnectSDK/Connect-SDK-iOS#80]
This is a more appropriate location and would help enable the use of a DeviceService subclass on it's own outside of Connect SDK.

**Comment by iadnan** [comment]
@iheart2code Can you please provide more details on this . Thanks.

**Comment by iheart2code** [comment]
Take [this enum](https://github.com/ConnectSDK/Connect-SDK-iOS-Core/blob/master/Devices/ConnectableDevice.h#L41-L50) and move it into the DeviceService.h file. It will mean that I can use WebOSTVService, etc without needed Connect SDK.

**Comment by iadnan** [comment]
Fixed as part of https://github.com/ConnectSDK/Connect-SDK-iOS-Core/commit/8fa1868ce7c6db57d20d7efd6f96a2461e9e0121
