### ISSUE TITLE
Add subtitle support

### ISSUE THREAD

**Issue by viveksekar** [ConnectSDK/Connect-SDK-iOS#91]
Support for the following formats - SRT, SUB, SMI, SSA, SAMI. With UTF-8 encoding.
CMB-918

**Comment by eunikolsky** [comment]
Android issue: https://github.com/ConnectSDK/Connect-SDK-Android/issues/214

**Comment by eunikolsky** [comment]
For DLNA, there is no specification for subtitles, so our implementation may not work on some devices.

For FireTV, we can send subtitles, but the user should manually enable one of them with the remote. There are no APIs to change/enable/disable subtitles in Fling SDK (at least, for the default player).

For Cast, based on experiments, the server is required to send the `Access-Control-Allow-Origin: *` response header. That is, the default `http.server` python3 module doesn't work, and a number of other web servers may not work either.

**Comment by eunikolsky** [comment]
To simplify tests and the `DLNAService` class, we should extract all the XML generation to another class.

**Comment by eunikolsky** [comment]
Merged into `dev` with https://github.com/ConnectSDK/Connect-SDK-iOS/pull/169.

**Comment by eunikolsky** [comment]
Need to add WebOS support as well.

**Comment by eunikolsky** [comment]
Merged into `dev` in https://github.com/ConnectSDK/Connect-SDK-iOS/commit/9e29d8341db5a2fbfe541b77d4573063aa942a2e and https://github.com/ConnectSDK/Connect-SDK-iOS-Lite/commit/51c1959296ef1b65a99d18bd153d5d72e61be04b.
